abstract_target 'Starter' do
  use_frameworks!
  # Pods for all targets
  pod 'MetaWear', :path => '../'

  target 'iOS' do
    platform :ios, '9.0'

    # Pods for iOS
    pod 'MBProgressHUD'
    
    #Pod for Twilio SMS
    pod 'Alamofire', '~> 4.0.1'
  end

  target 'macOS' do
    platform :osx, '10.12'

    # Pods for macOS
  end

  target 'tvOS' do
    platform :tvos, '10.0'

    # Pods for tvOS
    pod 'MBProgressHUD'
  end
end

